### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ejmorgan55** [agoldcheidt/Universal-Image-Generator-for-Berryboot#1]
Can't seem to get this to work. It installs the dependencies and libreelec; however, there is no method of selecting files to convert? Can you provide an explanation of how to select an OS to convert?

**Comment by ejmorgan55** [comment]
Still not working; how do you download a custom OS to this system?

**Comment by agoldcheidt** [comment]
Hi @ejmorgan55, thanks for report the issue, script fixed and updated.
