### ISSUE TITLE
Not working for Custom OS img (already in local directory)

### ISSUE THREAD

**Issue by smudgered** [agoldcheidt/Universal-Image-Generator-for-Berryboot#2]
Doesn't appear to have an option to select an already downloaded image and install custom image i.e. convert to squashfs etc 

Have put most recent DietPi img into os-selection folder to see if anything other than LibreElec shows up but no go.

Reason for trying this rather than just sticking with the July converted image is that the July DietPi converted image although it has cleared most of the hurdles nevertheless generates a swapfile warning during install and prompts user to file BugReport.

This may turn out to be trivial as I may be able to tidy this up in due course.

any advice welcome

**Comment by agoldcheidt** [comment]
Hi @smudgered, the script doesn't work like that. To add a new images, it require to add / edit a couple of lines but that's a good idea for future features. About DietPi, that image can update it itself to the latest version and runs great on my Raspberry Pi 3B+.

**Comment by Sprbb** [comment]
Plz add a manual to include multiple OSes.

**Comment by smudgered** [comment]
Hi Alex .Thanks for replying. I've come back to Berryboot,and your already converted images help make it more useful. But I'm still confused about what your script does exactly (despite reading it!)

Firstly on my laptop I'm openSUSE so  that's out, apparently, but never mind. I figure maybe I could use my rpi4 running raspiOS to  see what happens, or an Ubuntu Live USB. 

Use case 1 is to convert a downloaded openSUSE openSUSE-Leap-15.2-ARM-GNOME-raspberrypi4.aarch64-2020.07.08-Build1.71.raw.xz file and somehow make that compatible with required squashfs format, but I think that may be too  difficult. 

I could make a disk img of the USB created by flashing the openSUSE build. But I don't think that is what is intended either.

In fact I am completely in the dark! Can you enlighten me?

**Comment by agoldcheidt** [comment]
Hi @smudgered, basically this script followed [these steps](https://berryboot.alexgoldcheidt.com/go/berryboot-custom-images). The key to convert images for berryboot is: 1.- mount the boot partition and the rootfs partition. 2.- copy the boot partition content into the rootfs partition "boot" directory. 3.- comment the mount points in the rootfs partition /etc/fstab file. That will be enough.
