### ISSUE TITLE
Create other images

### ISSUE THREAD

**Issue by Sprbb** [agoldcheidt/Universal-Image-Generator-for-Berryboot#3]
Hi Alex,

Thank you for the image creater.
I am wondering if you could create a usermanual to add oter images.

Thank you in advance !

**Comment by bartoll** [comment]
Hi,

Yes, it would be great to read any manual or wiki.

I have tried this "generator" with a native Ubuntu image with no success.
I downloaded the source image from http://cdimage.ubuntu.com/ubuntu/releases/20.04.2/release/ubuntu-20.04.2-preinstalled-server-arm64+raspi.img.xz

**Comment by agoldcheidt** [comment]
Hi @bartoll, I'll add more OS images soon. In the meantime you can follow [these steps](https://berryboot.alexgoldcheidt.com/go/berryboot-custom-images)
